version: '3'
services:
  # Create frontend container
  frontend: # Name of our service
    build: ./todo-vue # path to dockerfile
    ports: # Port binding to host from docker container
      - "4173:4173" # Bind port 3000 of host to 3000 of container
    container_name: frontend-docker
    restart: always # What to do if container crashes
    links:
      - backend  # Create backend container
  backend:
    # Create backend container
    build: ./todo-nest
    ports:
      - "5000:5000"
    container_name: backend-docker
    restart: always